[tools]
node = "latest"
kind = "0.31.0"
pitchfork = "2.8.0"
python = "3.14.6"
pnpm = "10.33.0"
chezmoi = "2.70.1"
k9s = "0.50.18"
kubectx = "0.11.0"
helm = "4.1.4"
rust = "1.96.0"
aws = "2.32.11"
zoxide = "0.9.9"
neovim = "0.12.2"
